### ISSUE TITLE
Pipe output to a pager?

### ISSUE THREAD

**Issue by benjamin-thomas** [arches/table_print#48]
Hi, your gem looks great!

I need to visualize a lot of data. At the moment I get line wraps which is not workable.

Is it possible to pipe the output to a pager (like `less`) somehow ? (this is what `Hirb` does by default)

Or maybe how do I specify the screen width so that I don't get line wraps? 

That would allow one to scroll data with tmux or similar ?

Thanks!

**Comment by brauliobo** [comment]
+1, this should be the default when using pry/irb
