### ISSUE TITLE
Columns on seperate lines?

### ISSUE THREAD

**Issue by mawaldne** [arches/table_print#61]
This is more of a feature request. I looked through the config and couldn't find an option like this. Apologies if I missed it.

An option to have results such that each column of each row is on a separate line? (In postgres its call expanded table formatting - \x)

EG:
id |        email
----+----------------------
  1 | user@example.com
  2 | user2@example.com

would become:

-[ RECORD 1 ]---------------
id    | 1
email | user@example.com
-[ RECORD 2 ]---------------
id    | 2
email | user2@example.com

Great gem! I've been using it today and its awesome.

**Comment by arches** [comment]
maybe [awesome_print](http://rubygems.org/gems/awesome_print) would do this for you?
