### ISSUE TITLE
Column Name with Periods without association

### ISSUE THREAD

**Issue by wesleyk** [arches/table_print#68]
Is it possible to include periods in column names that aren't actually object associations?

Example failure:

```
>> tp [{ :"a.b" => 'c' }]
NoMethodError: undefined method `a' for {:"a.b"=>"c"}:Hash
```

This is on table_print 1.5.2 running on jruby 1.7.12.

**Comment by arches** [comment]
you can separate method and display name:

`tp User.all, "email" => {display_name: "e.m.a.i.l"}`

but that doesn't help you here.  I think your only option is a lambda:

```
> tp [{"a.b" => "c"}, {"a.b" => "d"}], "a.b" => lambda{|x| x["a.b"]}
A.B
---
c
d
```

**Comment by arches** [comment]
it's a little awkward because the displayname/method are switched in each case, sorry =\

```
"email" => {display_name: "e.m.a.i.l"} # hash key is method
"e.m.a.i.l" => lambda{|x| x.email} # hash key is column name
```

**Comment by wesleyk** [comment]
Ah okay, thanks! I'll try that out.
