### ISSUE TITLE
Multi line strings

### ISSUE THREAD

**Issue by fgarcia** [arches/table_print#72]
Look like by default, cells with multi-line strings are joined into a single one.

Is it possible to prevent this?

```ruby
h = { foo: 3, bar: "one line\nsecond" }
tp [h, h]
```

Generates:

```
FOO | BAR
----|----------------
3   | one line second
3   | one line second
```

**Comment by arches** [comment]
no, because what if you had more columns to the right?  you can't just leave the line break in there, you have to draw a second (or third, fourth, fifth) row underneath this one and figure out how to get the subsequent lines in the right place.  sorry!
